/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./components/nav/admin.vue')['default']
    AirportTask: typeof import('./components/History/AirportTask.vue')['default']
    Cockpit: typeof import('./components/Home/Cockpit.vue')['default']
    DeviceDetail: typeof import('./components/Home/DeviceDetail.vue')['default']
    DeviceItem: typeof import('./components/Home/DeviceItem.vue')['default']
    DeviceView: typeof import('./components/menu/DeviceView.vue')['default']
    DroneEquipment: typeof import('./components/History/DroneEquipment.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HistoryView: typeof import('./components/menu/HistoryView.vue')['default']
    HistoryViwe: typeof import('./components/menu/HistoryViwe.vue')['default']
    HomeView: typeof import('./components/menu/HomeView.vue')['default']
    PersonnelPanel: typeof import('./components/Home/PersonnelPanel.vue')['default']
    RightPanel: typeof import('./components/Home/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteView: typeof import('./components/menu/RouteView.vue')['default']
    SystemView: typeof import('./components/menu/SystemView.vue')['default']
    TakeOffSettings: typeof import('./components/Home/TakeOffSettings.vue')['default']
    TaskView: typeof import('./components/menu/TaskView.vue')['default']
  }
}
